language: ruby

sudo: false

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.6
  - 2.2.10
  - 2.3.7
  - 2.4.3
  - 2.5.1

gemfile:
  - gemfiles/Gemfile.activemodel-4.2
  - gemfiles/Gemfile.activemodel-5.0
  - gemfiles/Gemfile.activemodel-5.1
  - gemfiles/Gemfile.activemodel-5.2

matrix:
  exclude:
    - gemfile: gemfiles/Gemfile.activemodel-5.0
      rvm: 1.9.3
    - gemfile: gemfiles/Gemfile.activemodel-5.0
      rvm: 2.0.0
    - gemfile: gemfiles/Gemfile.activemodel-5.0
      rvm: 2.1.6
    - gemfile: gemfiles/Gemfile.activemodel-5.1
      rvm: 1.9.3
    - gemfile: gemfiles/Gemfile.activemodel-5.1
      rvm: 2.0.0
    - gemfile: gemfiles/Gemfile.activemodel-5.1
      rvm: 2.1.6
    - gemfile: gemfiles/Gemfile.activemodel-5.2
      rvm: 1.9.3
    - gemfile: gemfiles/Gemfile.activemodel-5.2
      rvm: 2.0.0
    - gemfile: gemfiles/Gemfile.activemodel-5.2
      rvm: 2.1.6

before_install:
  - gem install bundler

script: "echo 'COME ON!' && bundle exec rake spec"
